<?php echo $this->doctype() ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>

    <?php echo $this->headMeta() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <?php echo $this->placeholder('html5js') ?>

    <![endif]-->

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <?php echo $this->headScript() ?>

    <style type="text/css">
      body {
        padding-top: 40px;
      }
    </style>

    <!-- Le fav and touch icons -->
    <?php echo $this->placeholder('favicon') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">code.ign</a>
          <?php echo $this->navigation()->menu()->setUlClass('nav'); ?>
        </div>
      </div>

    </div>

    <div class="container">
      <?php echo $this->raw('content'); ?>

      <footer class="footer">
        <p class="pull-right"><a target="_blank" href="https://github.com/zendframework/zf2">Powered by Zend Framework 2</a></p>
        <p>&copy; 2011 - <?php echo date('Y') ?> by <a target="_blank" href="http://corp.ign.com/">IGN Entertainment, Inc.</a> All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
