<div class="row">
    <div class="span12">
        <blockquote>
            <p>A group of programmers walk into a bar. The bar tender asks, "What'll it be?"</p>
            <p>The C programmer says, "You see that bottle?" pointing to a large green bottle marked only with a "*". "Give me whatever's in it."</p>
            <p>The Lisp programmer says, "Give me (on the bar in front of me) a glass (a small glass (or plastic cup)) of (imported (German)) beer. (If that's not available, then wine (red (California (Cabernet))).)</p>
            <p>The assembly language programmer says, "Take a glass from position two in the glass rack and place it on the bar in position zero (in front of you). Take a bottle from position seven in the bottle rack and pour the contents into position zero on the bar. Stop after three seconds. Put the bottle in position seven of the bottle rack. Take the glass from position zero on the bar and place it in position four on the bar (in front of me)."</p>
            <p>The Smalltalk programmer says, "Bartender get vodka bottle. Vodka bottle pour into glass. Hand lift glass. Mouth drink."</p>
            <p>The Visual Basic programmer says, "You see those two guys sitting over there?" pointing at a big bald guy and a smaller one wearing glasses. "I'll take whatever they're willing to let me have."</p>
            <p>The SQL programmer says, "Take all the bottles containing beer, call them 'beers'. Take all the bottles that come from companies with output of less than one million units per year, call them 'micros'. Take the intersection of 'beers' and 'micros', and pour me the first one."</p>
            <p>The Forth programmer says, "White wine, give me."</p>
            <p>The Prolog programmer says, "I'll have coke if I want caffeine. I'll have vodka if I want to get drunk. I'll have water if I'm thirsty. I want caffeine if I need to stay awake. I'm thirsty if it's a hot day. I need to stay awake if I still have work to do today. It's a hot day if it's greater than 80 degrees Fahrenheit. I still have work to do today."</p>
            <p>The UI designer says, "I'd like a small glass with a thin edge so it's easy to drink from. It should be large enough to grasp easily, but not so large that it's too heavy. It should have a picture on it of a person drinking (thus showing how to use the glass)." "But what do you want in it?" asks the bar tender. "I don't care," says the UI designer.</p>
            <p>The manager says, "Oh, just give me a drink!"</p>
            <small><a href="http://www.mememotes.com/meme_motes/2005/07/a_group_of_prog.html" target="_blank">http://www.mememotes.com/meme_motes/2005/07/a_group_of_prog.html</a></small>
        </blockquote>
    </div>
</div>
