</div> <!-- close off the .container div to give us full screen access -->

	<?php echo $this->headLink()->appendStylesheet( 'http://fonts.googleapis.com/css?family=Fredericka+the+Great|Open+Sans+Condensed:700' ); ?>
	<?php echo $this->headLink()->appendStylesheet( '/css/code-foo.css' ); ?>
	
	<?php echo $this->headScript()->appendFile( '/js/jquery-1.7.1.min.js' ); ?>
	<?php echo $this->headScript()->appendFile( '/js/jquery-code-foo-controller.js' ); ?>
	<!-- Code-Foo -->
		
		<div class="row-fluid cf-header-container">
			<div class="container">
				
				<div class="cf-ribbon-container">
					<div class="cf-ribbon">
						<span class="line year">2012</span>
						<span class="line start-date">July<small>11</small></span>
						<span class="line small">-</span>
						<span class="line end-date">Aug<small>22</small></span>
					</div>
					<div class="ribbon-hash"></div>
				</div>
			
				<h1>Code <span>Foo</span><sup>2</sup></h1>
				<h3>Six weeks of tech training @ign,<br />working on real projects with cutting-edge tech. <a href="#" class="apply-now">apply now</a></h3>
			</div>
		</div>
		
		<div class="row cf-subhead">
			<div class="container">
				<h4>What is Code-Foo?</h4>
				<div class="span4">
					<strong>The Tech</strong>
					<p>
					    Lorem ipsum dolor sit amet, id suspendisse enim 
					    ipsum ante, cras sed egestas lorem scelerisque sodales 
					    tincidunt, ratione erat, nunc sit non velit ut quisque, 
					    odio nunc vel at nec porttitor donec. Integer morbi.Praesent 
					    consectetuer, pulvinar nunc congue vulputate.
					</p>
				</div>
				<div class="span4">
					<strong>The Development</strong>
					<p>
					    Lorem ipsum dolor sit amet, id suspendisse enim 
					    ipsum ante, cras sed egestas lorem scelerisque sodales 
					    tincidunt, ratione erat, nunc sit non velit ut quisque, 
					    odio nunc vel at nec porttitor donec. Integer morbi.Praesent 
					    consectetuer, pulvinar nunc congue vulputate.
					</p>
				</div>
				<div class="span4">
					<strong>The Result</strong>
					<p>
					    Lorem ipsum dolor sit amet, id suspendisse enim 
					    ipsum ante, cras sed egestas lorem scelerisque sodales 
					    tincidunt, ratione erat, nunc sit non velit ut quisque, 
					    odio nunc vel at nec porttitor donec. Integer morbi.Praesent 
					    consectetuer, pulvinar nunc congue vulputate.
					</p>
				</div>
			</div>
		</div>
		
		<div class="row-fluid cf-culture">
			<div class="container">
				<div class="culture-bookmark"></div>
				<div class="main-image-container">
					<img src="/images/code-foo/gallery-01-large.jpg" alt="gallery-01-large" width="460" height="295" />
				</div>
				<ul class="image-gallery">
					<li><a href="#"><img src="/images/code-foo/gallery-02-small.jpg" alt="gallery-02-small" width="140" height="140" /></a></li>
					<li><a href="#"><img src="/images/code-foo/gallery-03-small.jpg" alt="gallery-03-small" width="140" height="140" /></a></li>
				</ul>
				<div class="span4">
					<strong>The Culture</strong>
					<p>
						Lorem ipsum dolor sit amet, id suspendisse enim ipsum ante, 
						cras sed egestas lorem scelerisque sodales tincidunt, ratione 
						erat, nunc sit non velit ut quisque, odio nunc vel at nec porttitor 
						donec. Integer morbi.Praesent consectetuer, pulvinar nunc congue 
						vulputate.
					</p>
					<p>
						Want to see more? <a href="#">Check out the tour of our offices as performed by Peer</a>. 
					</p>
				</div>
			</div>
		</div>
		
		<div class="row cf-speakers">
			<div class="container">
				<h4>Speakers</h4>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
			</div>
		</div>
	
		<div class="application-overlay row-fluid">
			<div class="container">
				<div class="header">
					<h2>Application</h2>
					<p>
						Lorem ipsum dolor sit amet, id suspendisse enim ipsum ante, 
						cras sed egestas lorem scelerisque sodales tincidunt, ratione 
						erat, nunc sit non velit ut quisque, odio nunc vel at nec porttitor 
						donec. Submit it to <a href="#">github</a>.
					</p>
				</div>
				<ul>
					<li>
						<strong class="num">1.</strong>
						<p>
							How many ping pong balls would it take to fill an average-sized
							school bus? Describe each step in your thought process.
						</p>
					</li>
					<li>
						<strong class="num">2.</strong>
						<p>
							Create a liquid layout with HTML, CSS, and Javascript. This layout
							must support the following resolutions: <strong>1024x768</strong>,
							<strong>1680x1050</strong>. Explain why you would use a liquid layout.
						</p>
					</li>
					<li>
						<strong class="num">3.</strong>
						<p>
							You own a license plate manufacturing company. Given a population, 
							determine the simplest pattern that will produce enough unique
							plates. Since all the plates that match the pattern will be 
							generated, find the pattern that produces the least excess plates.
							Use a combination of letters (A-Z) and numbers (0-9).
						</p>
						<div class="examples">
							<ul>
							    <li><strong>Example 1</strong></li>
							    <li>Population: <span>10</span></li>
							    <li>Pattern: <span>1 number</span></li>
							    <li>Total Plates: <span>10</span></li>
							    <li>Excess Plates: <span>0</span></li>
							</ul>
							<ul>
							    <li><strong>Example 2</strong></li>
							    <li>Population: <span>25</span></li>
							    <li>Pattern: <span>1 letter</span></li>
							    <li>Total Plates: <span>26</span></li>
							    <li>Excess Plates: <span>1</span></li>
							</ul>
						</div>
					</li>
					<li>
						<strong class="num">4.</strong>
						<p>
							Submit a short video (less than 2 minutes) introducing yourself and 
							telling us why you're a good fit for IGN and Code-Foo.
						</p>
					</li>
					<li>
						<strong class="bonus">Bonus</strong>
						<p>
							Programmatically create a game of Connect 4&trade; with one
							AI-controlled opponent and a human-controlled player.
						</p>
					</li>
				</ul>
			</div>
		</div>
	
		<!-- /Code-Foo -->
<div class="container"> <!-- start a container div -->
