</div> <!-- close off the .container div to give us full screen access -->

	<?php echo $this->headLink()->appendStylesheet( 'http://fonts.googleapis.com/css?family=Fredericka+the+Great|Open+Sans+Condensed:700' ); ?>
	<?php echo $this->headLink()->appendStylesheet( '/css/code-foo.css' ); ?>
	
	<?php echo $this->headScript()->appendFile( '/js/jquery-1.7.1.min.js' ); ?>
	<?php echo $this->headScript()->appendFile( '/js/jquery-code-foo-controller.js' ); ?>
	<!-- Code-Foo -->
		
		<div class="row-fluid cf-header-container">
			<div class="container">
				
				<div class="cf-ribbon-container">
					<div class="cf-ribbon">
						<span class="line year">2012</span>
						<span class="line start-date">July<small>11</small></span>
						<span class="line small">-</span>
						<span class="line end-date">Aug<small>22</small></span>
					</div>
					<div class="ribbon-hash"></div>
				</div>
			
				<h1>Code <span>Foo</span><sup>2</sup></h1>
				<h3>Six weeks of tech training @ign,<br />working on real engineering projects with cutting-edge tech.<br />
				Blow our minds while you're here and we'll hire you. No kidding. <a href="#" class="apply-now">apply now</a></h3>
			</div>
		</div>
		
		<div class="row cf-subhead">
			<div class="container">
				<h4>What is Code-Foo?</h4>
				<div class="span4">
					<strong>The Program</strong>
					<p>
						Code-Foo is a six-week program where you'll get paid to learn
					    cutting-edge tech and have the opportunity to work on real 
					    IGN engineering projects.
					    While you're here you'll be
					    trained by today's industry leaders in a conference-style setting. Next,
					    you'll have time dedicated to work in small teams on real projects.
					</p>
				</div>
				<div class="span4">
					<strong>The Tech Stack</strong>
					<p>
					    We don't care about your official credentials. In fact, we won't even
					    accept a resume. You do need to be able to code - and be passionate about IGN.
					    We use the right tool for the job which means
					    you'll get the chance to work with Ruby on Rails, Scala, Java,
					    MongoDB, jQuery, PHP, HTML5, and CSS3 - just to name a few. 
					</p>
				</div>
				<div class="span4">
					<strong>The Result</strong>
					<p>
						Sure, learning tech and getting some killer swag is great, but while you're here you'll also
						have the opportunity to get certified in languages you're
						most proficient in. We'll even help you find a gig, 
						if we don't hire you ourselves. 
					</p>
					<p>
						<a href="http://www.fastcompany.com/magazine/160/ign-self-taught-coders" target="_blank">Code-Foo Success in Fast Company Magazine &raquo;</a> 
					</p>
				</div>
			</div>
		</div>
		
		<div class="row-fluid cf-culture">
			<div class="container">
				<div class="culture-bookmark"></div>
				<div class="main-image-container">
					<img src="/images/code-foo/gallery-01-large.jpg" alt="gallery-01-large" width="460" height="295" />
				</div>
				<ul class="image-gallery">
					<li><a href="/images/code-foo/gallery-01-large.jpg" class="gallery-link-one active"></a></li>
					<li><a href="/images/code-foo/gallery-02-large.jpg" class="gallery-link-two"></a></li>
					<li><a href="/images/code-foo/gallery-03-large.jpg" class="gallery-link-three"></a></li>
					<li><a href="/images/code-foo/gallery-04-large.jpg" class="gallery-link-four"></a></li>
				</ul>
				<div class="span4">
					<strong>The Culture</strong>
					<p>
						At IGN we have 24.1 million viewers per month. We may be big time, but 
						we work in small teams allowing our employees to have big impact. 
						We have fun because we're passionate about the industry and what we do; 
						we know what our users want because we are our users.
					</p>
					<p>
						Don't get lost among countless aisles of cubicles. At IGN, we expect
						you to speak your mind, lead shenanigans, and know that nothing here
						is above question.
					</p>
					<p>
						Want to see more? <a href="http://go.ign.com/gHjKlm" target="_blank">Check out the tour of our offices as performed by Peer</a>. 
					</p>
				</div>
			</div>
		</div>
		
		<div class="row cf-speakers">
			<div class="container">
				<h4>Speakers</h4>
				<div class="span2 manishPandit">
					<a href="http://twitter.com/#!/lobster1234" target="_blank">
						<span>Manish Pandit</span>
					</a>
				</div>
				<div class="span2 adamPassey">
					<a href="http://twitter.com/#!/adampassey" target="_blank">
						<span>Adam Passey</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
				<div class="span2">
					<a href="#">
						<span>To Be Announced</span>
					</a>
				</div>
			</div>
		</div>
	
		<div class="application-overlay row-fluid">
			<div class="container">
				<div class="header">
					<h2>Application</h2>
					<p>
						Answer the questions below and push them to a <a href="http://github.com" target="_blank">github</a>
						repository. Then, send us an email with a link to your repository at
						<a href="mailto:code-foo@ign.com">code-foo@ign.com</a> by <strong>April 30<sup>th</sup> 2012</strong>.
						We'll notify you by May 18<sup>th</sup> if you've made the cut.
					</p>
				</div>
				<ul>
					<li>
						<strong class="num">1.</strong>
						<p>
							How many ping pong balls would it take to fill an average-sized
							school bus? Describe each step in your thought process.
						</p>
					</li>
					<li>
						<strong class="num">2.</strong>
						<p>
							Create a liquid layout with HTML, CSS, and Javascript. This layout
							must support the following resolutions: <strong>1024x768</strong>,
							<strong>1680x1050</strong>. Explain why you would use a liquid layout.
						</p>
					</li>
					<li>
						<strong class="num">3.</strong>
						<p>
							You own a license plate manufacturing company. Given a population, 
							determine the simplest pattern that will produce enough unique
							plates. Since all the plates that match the pattern will be 
							generated, find the pattern that produces the least excess plates.
							Use a combination of letters (A-Z) and numbers (0-9).
						</p>
						<div class="examples">
							<ul>
							    <li><strong>Example 1</strong></li>
							    <li>Population: <span>10</span></li>
							    <li>Pattern: <span>1 number</span></li>
							    <li>Total Plates: <span>10</span></li>
							    <li>Excess Plates: <span>0</span></li>
							</ul>
							<ul>
							    <li><strong>Example 2</strong></li>
							    <li>Population: <span>25</span></li>
							    <li>Pattern: <span>1 letter</span></li>
							    <li>Total Plates: <span>26</span></li>
							    <li>Excess Plates: <span>1</span></li>
							</ul>
						</div>
					</li>
					<li>
						<strong class="num">4.</strong>
						<p>
							Submit a short video (less than 2 minutes) introducing yourself, showing your passion for IGN, and 
							telling us why you're a good fit for Code-Foo.
						</p>
					</li>
					<li>
						<strong class="bonus">Bonus</strong>
						<p>
							Programmatically create a game of Connect 4&trade; with one
							AI-controlled opponent and a human-controlled player.
						</p>
					</li>
				</ul>
			</div>
		</div>
	
		<!-- /Code-Foo -->
<div class="container"> <!-- start a container div -->
