<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                          => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'      => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\JobsController'       => __DIR__ . '/src/Application/Controller/JobsController.php',
    'Application\Model\Resumator\Feed'            => __DIR__ . '/src/Application/Model/Resumator/Feed.php',
    'Application\Model\Resumator\Job'             => __DIR__ . '/src/Application/Model/Resumator/Job.php',
    'Application\Mvc\Controller\ActionController' => __DIR__ . '/src/Application/Mvc/Controller/ActionController.php',
);