<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                          => __DIR__ . '/Module.php',
    'Application\Controller\ErrorController'      => __DIR__ . '/src/Application/Controller/ErrorController.php',
    'Application\Controller\IndexController'      => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\JobsController'       => __DIR__ . '/src/Application/Controller/JobsController.php',
    'Application\Mvc\Controller\ActionController' => __DIR__ . '/src/Application/Mvc/Controller/ActionController.php',
    'Application\View\Listener'                   => __DIR__ . '/src/Application/View/Listener.php',
);