  <div class="hero-unit">
    <h1>Welcome to code.ign</h1>
    <p>This site contains the latest from IGN Engineering. Learn more about <a href="<?php echo $this->url('blog') ?>">what we do</a>, <a href="<?php echo $this->url('people') ?>">who we are</a>, and how you can <a href="<?php echo $this->url('jobs') ?>">join our team</a>!</p>
    <p><a class="btn primary large" href="https://github.com/ign/code.ign.com">Behind this site &raquo;</a></p>
  </div>

  <div class="row">
    <div class="span4">
      <h2>Nicholas Calugar</h2>
      <?php echo $this->gravatar('njcalugar@gmail.com', array('img_size' => 200)); ?>
    </div>
    <div class="span4">
      <h2>Jon Tai</h2>
      <?php echo $this->gravatar('jon.tai@gmail.com', array('img_size' => 200)); ?>
    </div>
    <div class="span4">
      <h2>Nicholas Calugar</h2>
      <?php echo $this->gravatar('njcalugar@gmail.com', array('img_size' => 200)); ?>
    </div>
    <div class="span4">
      <h2>Jon Tai</h2>
      <?php echo $this->gravatar('jon.tai@gmail.com', array('img_size' => 200)); ?>
    </div>
  </div>
