  <div class="hero-unit">
    <h1>Welcome to code.ign</h1>
    <p>This site contains the latest from IGN Engineering. Learn more about <a href="<?php echo $this->url('blog') ?>">what we do</a>, <a href="<?php echo $this->url('people') ?>">who we are</a>, and how you can <a href="<?php echo $this->url('jobs') ?>">join our team</a>!</p>
    <p><a class="btn primary large" href="https://github.com/ign/code.ign.com">Behind this site &raquo;</a></p>
  </div>

  <div class="row">
    <div class="span8">
      <div class="row">
        <div class="span4">
          <h2>Latest Blog Posts</h2>
          <p>We have a lot of smart engineers! Read posts from our engineers including what we are working on and what we are playing.</p>
          <p><a class="btn" href="<?php echo $this->url('blog') ?>">IGN Engineering Blog &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Meet our Engineers</h2>
          <p>We are real people! We push code, contribute to the open-source projects, speak at meetups, and play games.</p>
          <p><a class="btn" href="<?php echo $this->url('people') ?>">IGN Engineers &raquo;</a></p>
        </div>
      </div>
      <div class="row">
        <div class="span4">
          <h2>IGN Engineering Jobs</h2>
          <p>We are always hiring! Check out our current openings or tell us why we need YOU on our team.</p>
          <p><a class="btn" href="<?php echo $this->url('jobs') ?>">IGN Engineering Jobs &raquo;</a></p>
        </div>
      </div>
    </div>
    <div class="span4">
      <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
        new TWTR.Widget({
          version: 2,
          type: 'profile',
          rpp: 6,
          interval: 30000,
          width: 300,
          height: 300,
          theme: {
            shell: {
              background: '#333333',
              color: '#ffffff'
            },
            tweets: {
              background: '#f5f5f5',
              color: '#000000',
              links: '#0088cc'
            }
          },
          features: {
            scrollbar: false,
            loop: false,
            live: false,
            behavior: 'all'
          }
        }).render().setUser('socalnick').start();
      </script>
    </div>
  </div>
